README.md

chore: add public preview notice

---

README.md

The README should say that this software is not yet ready for production.

doc: Add preview disclaimer to the README

---

config/crd/bases/cloudsql.cloud.google.com_authproxyworkloads.yaml
config/rbac/role.yaml
config/webhook/manifests.yaml
installer/cloud-sql-proxy-operator.yaml

chore: release 0.2.0

---

Makefile
infra/run.sh

Creates a new run.sh script to provision resources for the local
development and for e2e build job. Call this script from the Makefile with
appropriate values.

feat: add script to run the terraform, with input validation.

---

docs/examples/deployment-postgres-tcp.yaml
internal/testhelpers/resources.go
internal/testhelpers/testcases.go
tests/e2e_test.go
tests/setup_test.go

Adds an e2e test that actually connects to the postgres database and executes a query.
Related-to: #52

test: E2E database connection test for postgres

---

config/crd/bases/cloudsql.cloud.google.com_authproxyworkloads.yaml
installer/cloud-sql-proxy-operator.yaml

controller-gen is now version 0.11.3

chore: update version of controller-gen

---

Makefile

Ensure that the URL for `cloud-sql-proxy-operator.yaml` is updated to the current version.

doc: Ensure that URLs in the docs have the current version.

---

README.md

Updating broken link in README.

docs: update releases link in README

---

Makefile
config/crd/bases/cloudsql.cloud.google.com_authproxyworkloads.yaml
installer/cloud-sql-proxy-operator.yaml

Manual upgrade required because of code generation.

chore(deps): update dependency sigs.k8s.io/controller-tools to v0.11.3

---

.github/workflows/build.yaml
.github/workflows/tests.yaml
infra/permissions/main.tf
infra/resources/main.tf
tools/e2e_test_job.sh

ci: run e2e tests using WIF and Github Actions

---

README.md
docs/quick-start.md

Update readme and quick start documentation to use version v0.4.0

doc: update readme sample code to use v0.4.0

---

internal/workload/podspec_updates.go

doc: improve code comment in FindMatchingAuthProxyWorkloads

---

Makefile
docs/api.md

Manual update of this library, includes changes to generated api documentation.

chore(deps): update crd-ref-docs tool to 0.0.9

---

.github/flakybot.yaml
.github/workflows/tests-main.yaml
.gitignore
Makefile

chore: add flakybot

---

.github/renovate.json

chore: correct renovate.json config

---

internal/workload/podspec_updates.go
internal/workload/podspec_updates_test.go

Fixes #441 
Related to #361
Related to [cloud-sql-proxy #1943](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/1943)

feat: Configure containerPort on proxy pod when telemetry is enabled

---

README.md

docs: Fix broken link in README.

---

.github/renovate.json
.github/trusted-contribution.yml
.github/workflows/tests.yaml

Improve the renvoate configuration to combine dependencies related to build tools, and kubernetes.
Fixes #465.

chore: Update renovate configuration to combine deps.

---

.github/workflows/tests-main.yaml

Disabling flakybot as Pub/Sub topic for it has been deleted causing step to fail.

ci: disable flakybot

---

.github/workflows/tests-main.yaml

Missed unit tests as part of #484

ci: disable flakybot on unit tests

---

.github/workflows/tests-main.yaml

Reverts GoogleCloudPlatform/cloud-sql-proxy-operator#484

ci: re-enable flakybot

---

.github/release-please.yml
README.md
docs/quick-start.md

chore: automate docs version bumps

---

internal/workload/podspec_updates.go

Updates the proxy release version to 2.15.2.

fix: Update proxy to 2.15.2.
