Makefile
tools/release-pr-generate.sh

When a user lands on this repo and reads the README or Quick Start Guide, the instructions
should point the user to the latest released version of the proxy, not the current dev version.
This PR updates `make generate` so that it does not automatically update the version in documentation,
leaving the latest release version in the docs.
It also updates the release-please-updates job that generates code after the release PR is
created to update the version in docs along with running `make generate`

chore: only update the version in the docs on a new release.

---

README.md

Fixes n/a (I'm skipping as this is a minor fix)
Hi, this is just a small fix on two links in `README.md`. You can also preview the change on the forked branch: https://github.com/shuuji3/cloud-sql-proxy-operator/tree/docs-fix-links#readme
**before**
**after**

docs: fix two minor links

---

README.md
docs/quick-start.md

This updates the Quick Start guide adding a few extra steps to work around 
the problem that the installer does not work on GKE Autopilot clusters. 
This explains to the user how to use the helm chart for cert-manager to make it
install correctly on GKE. 
Related to #157

doc: update the Quick Start guide with the workaround for GKE Autopilot 

---

config/crd/bases/cloudsql.cloud.google.com_authproxyworkloads.yaml
installer/cloud-sql-proxy-operator.yaml
internal/api/v1alpha1/authproxyworkload_types.go
internal/controller/authproxyworkload_controller.go
internal/controller/authproxyworkload_controller_test.go

For security, AuthProxyWorkload resources are only allowed to affect workloads running
in the same namespace. This prevents one AuthProxyWorkload in one namespace from affecting
a workload in a different namespace. 
This change removes the WorkloadSelectorSpec.Namespace field and associated code that allowed
cross-namespace workload selection.

fix!: remove Namespace field from AuthProxyWorkloadSelector

---

config/crd/bases/cloudsql.cloud.google.com_authproxyworkloads.yaml
config/rbac/role.yaml
config/webhook/manifests.yaml
installer/cloud-sql-proxy-operator.yaml

The copyright header on generated files need to read the current year. Otherwise, lint tests
will fail.

chore: update copyright in generated files to 2023

---

Makefile
docs/quick-start.md
installer/install.sh
tools/install.sh

This updates the install script to use helm to install cert-manager. This makes the installer work both for 
GKE Autopilot and non-autopilot clusters.
Fixes #157

fix: Update installer.sh to use helm for cert-manager

---

internal/workload/podspec_updates.go

The proxy release is complete. Now we must update the operator to deploy the proxy image 2.0.0.

chore: update to use latest proxy image: 2.0.0

---

infra/permissions/main.tf
infra/permissions/vars.tf

This moves the terraform code that sets up the GCP project APIs and permissions into a separate
terraform project. This will simplify the automated e2e testing jobs. 
Related to #65

feat: separate terraform for project setup and permissions 

---

.github/header-checker-lint.yml
infra/resources/.gitignore
infra/resources/artifacts.tf
infra/resources/database.tf
infra/resources/gke_cluster.tf
infra/resources/main.tf
infra/resources/vars.tf

This is a copy of the resource provisioning code from `testinfra/*.tf` with this modification: IAM and permissions 
related terraform code is in the `infra/permissions` terraform project. 
Related to #65

feat: Add new terraform project for e2e test resources

---

docs/examples/deployment-mssql-tcp.yaml
docs/examples/deployment-mysql-tcp.yaml

Adds additional doc examples demonstrating how to connect to MySQL and MS SQL Server using the Cloud SQL Proxy Operator.
This is needed for the quickstart guides that are being published this week.

doc: add examples to connect to MySQL and MS SQL Server

---

infra/resources/database.tf
infra/resources/main.tf
internal/testhelpers/resources.go
internal/testhelpers/testcases.go
tests/e2e_test.go
tests/setup_test.go

Adds terraform code and E2E test cases that connect and run a query on MySQL and MS SQL Server databases. 
Related-to: #52

test: Add E2E db connection tests for mysql and mssql

---

config/rbac/role.yaml
installer/cloud-sql-proxy-operator.yaml
internal/api/v1alpha1/authproxyworkload_types.go
internal/controller/authproxyworkload_controller.go
internal/controller/authproxyworkload_controller_test.go
internal/workload/podspec_updates.go
internal/workload/podspec_updates_test.go
tests/e2e_test.go

Given an AuthProxyWorkload resource that has been applied to StatefulSet, DaemonSet, 
ReplicaSet, and/or Deployment workloads, when that AuthProxyWorkload is updated, the operator 
will add or modify an annotation on the PodTemplateSpec of that workload, causing k8s to
replace the workload's pods following the workload's rollout strategy, thus applying the
AuthProxyWorkload's configuration change.  
Related to #187. 
The code for this feature will be split across a few PRs for clarity. These are the first 4:
1. (This PR) Automatically rollout pod changes on AuthProxyWorkload update.
2. Automatically rollout pod changes on AuthProxyWorkload delete.
3. Add `AutomaticRolloutEnabled` field to the AuthProxyWorkload resource.
4. Update AuthProxyWorkload status conditions to show if a workload …

feat: Automatically trigger pod rollout for appsv1 resources when AuthProxyWorkload changes.

---

internal/controller/authproxyworkload_controller.go
internal/controller/authproxyworkload_controller_test.go
internal/testhelpers/resources.go
internal/testhelpers/testcases.go
internal/testintegration/integration_test.go
internal/workload/podspec_updates.go
internal/workload/podspec_updates_test.go
tests/e2e_test.go

When an AuthProxyWorkload is deleted, automatically update all related workloads that support automatic
rollout: Deployment, StatefulSet, DaemonSet, ReplicaSet.

feat: automatic  changes to workloads when an AuthProxyWorload is deleted

---

config/crd/bases/cloudsql.cloud.google.com_authproxyworkloads.yaml
installer/cloud-sql-proxy-operator.yaml
internal/api/v1alpha1/authproxyworkload_types.go
internal/api/v1alpha1/authproxyworkload_webhook.go
internal/controller/authproxyworkload_controller.go
internal/controller/authproxyworkload_controller_test.go
internal/workload/podspec_updates.go

Adds a new field `RolloutStrategy` to the AuthProxyWorkload that will allow users to control how
the operator will roll out changes when an AuthProxyWorkload is updated.
`RolloutStrategy` has two possible values: 
- `Workload` in which the operator will automatically follow the behavior of the Strategy set on the workload.
- `None` in which the operator will not attempt to roll out changes

feat: add new field RolloutStrategy control automatic rollout

---

internal/workload/podspec_updates.go
internal/workload/podspec_updates_test.go

Use environment variables instead of CLI flags to configure the global proxy settings
for proxy containers.

chore: use environment vars to configure global proxy settings

---

internal/api/v1alpha1/authproxyworkload_test.go
internal/api/v1alpha1/authproxyworkload_webhook.go

We do not allow a user to change the selector of an AuthProxyWorkload, as it will require the operator to do
too much bookkeeping. We can keep our code clean and simple if the operator assumes that the
workload selected for a proxy configuration never changes. 
Related to #36

feat: Validate AuthProxyWorkload updates to prevent changes to the workload selector.

---

config/crd/bases/cloudsql.cloud.google.com_authproxyworkloads.yaml
docs/authproxyworkload-reference.md
installer/cloud-sql-proxy-operator.yaml
internal/api/v1alpha1/authproxyworkload_types.go
internal/testhelpers/resources.go
internal/workload/names.go
internal/workload/names_test.go
internal/workload/podspec_updates.go
internal/workload/podspec_updates_test.go
tests/e2e_test.go

The operator will configure the pod with a proxy that listens on a unix socket. The operator will mount the
parent directory of each instance's `unixSocketPath` to each container in the pod. When the proxy starts, it 
will create a unix socket for the instance in that mounted directory.
Care should be take to ensure that the parent directory can safely be used across all containers in the pod.
Fixes #47

feat: Add support for Unix sockets.

---

.github/workflows/release-please-updates.yaml

chore: bump go version in release job

---

internal/api/v1alpha1/authproxyworkload_test.go
internal/api/v1alpha1/authproxyworkload_webhook.go

RolloutStrategy controls when and how changes to the AuthProxyWorkload are rolled out to 
running workloads. Changing this value after creation would cause an inconsistent rollout state. 
Related to #36

feat: Updating the RolloutStrategy field is not allowed.

---

Makefile
README.md
config/crd/bases/cloudsql.cloud.google.com_authproxyworkloads.yaml
docs/api.md
installer/cloud-sql-proxy-operator.yaml
internal/api/v1alpha1/authproxyworkload_types.go
internal/api/v1alpha1/groupversion_info.go
internal/api/v1alpha1/zz_generated.deepcopy.go
tools/config-crd-ref-docs.yaml

This will automatically generate API documentation for the AuthProxyWorkload CRD
and put it into the source code at `docs/api.md`. This uses the tool 
[crd-ref-docs](https://github.com/elastic/crd-ref-docs). The api docs are generated
automatically during `make generate` so that the docs commited to the source code 
are always in sync with go source. 
Fixes #165

doc: Automatically generate API documentation for the AuthProxyWorkload

---

config/crd/bases/cloudsql.cloud.google.com_authproxyworkloads.yaml
installer/cloud-sql-proxy-operator.yaml
internal/api/v1alpha1/authproxyworkload_test.go
internal/api/v1alpha1/authproxyworkload_types.go
internal/api/v1alpha1/authproxyworkload_webhook.go

Validates the fields on InstanceSpec to ensure that values are valid and consistent.
Fixes #36

feat: Validate instance fields

---

.gitignore
Dockerfile-operator
Makefile

The OSS community and licenses require us to include a copy of the license for linked open-source licenses
in our distribution. The docker image is our only binary artifact. This bundles a copy of the license for this project, 
and all linked dependencies into the docker image.

chore: Bundle third party licenses into docker image.

---

Makefile

Remove conflicting tool versions that were the result of a bad rebase.
For kubectl, use the official kubernetes release version from the repo:
github.com/kubernetes/kubernetes

fix: Repair a bad merge of tool versions in the Makefile.

---

internal/controller/authproxyworkload_controller_test.go
internal/controller/setup.go
internal/testhelpers/resources.go
internal/workload/names_test.go
internal/workload/podspec_updates_test.go

Update all files to use the import alias `cloudsqlapi` for the package
"github.com/GoogleCloudPlatform/cloud-sql-proxy-operator/internal/api/v1alpha1".
The API package name is going to change from `v1alpha1` to `v1` soon and we don't want a ton 
of irrelevant changes throughout the files. Thus, we want to use the package alias throughout the
code so that the package rename change is concise.

chore: Use package alias cloudsqlapi for ./internal/api/v1alpha

---

config/crd/bases/cloudsql.cloud.google.com_authproxyworkloads.yaml
docs/api.md
installer/cloud-sql-proxy-operator.yaml
internal/api/v1alpha1/authproxyworkload_types.go
internal/controller/authproxyworkload_controller.go
internal/controller/authproxyworkload_controller_test.go
internal/controller/pod_controller_test.go
internal/controller/setup.go
internal/testintegration/setup.go
internal/workload/podspec_updates.go
internal/workload/podspec_updates_test.go
main.go

When an AuthProxyWorkload uses the default proxy image, use the operator's default proxy image 
and the AuthProxyWorkload.Generation together as a key to determine if a workload's proxy containers
need to be updated. 
Add tests to ensure that when the default image hardcoded into the operator changes, workloads using 
the old default will be identified and reconfigured properly.
There is another PR coming after this one which will automatically check and apply configuration 
changes to AuthProxyWorkload resources on operator startup.
Related to #87

feat: When the operator's default proxy image changes, workload containers should be updated.

---

internal/controller/proxy_image_upgrade.go
internal/controller/setup.go
internal/testintegration/integration_test.go
internal/testintegration/setup.go

When the operator starts, run a function that will list all AuthProxyWorkloads, find ones that are using the
default proxy image, and trigger an update on those AuthProxyWorkloads. This will cause the Reconcile 
function to ensure that the AuthProxyWorkloads are running the latest default version of the proxy image. 
Fixes #87

feat: Automatically update default images on operator startup.

---

.golangci.yml

Configure the linter to make sure that go code always imports 
`github.com/GoogleCloudPlatform/cloud-sql-proxy-operator/internal/api/v1alpha1` 
with the alias `cloudsqlapi`.

chore: lint for use of cloudsqlapi package alias

---

Makefile
installer/install.sh
tools/helm-install-certmanager.sh

This upgrades the cluster to cert-manager 1.11.0, adds comments so that cert-manager
is automatically upgraded by renovate.
Also, this moves e2e helm script commands out of the Makefile and into their own shell script.
The helm-related commands  had grown too complex for a Makefile target.

chore: Upgrade to cert-manager 1.11.0

---

config/crd/bases/cloudsql.cloud.google.com_authproxyworkloads.yaml
installer/cloud-sql-proxy-operator.yaml
internal/api/v1/authproxyworkload_test.go
internal/api/v1/authproxyworkload_types.go
internal/api/v1/authproxyworkload_webhook.go

Validation generated by kubebuilder:Enum does not work with []string fields because it applies to the entire value, not the elements of the slice.

fix: Validate the AdminServer.EnableAPIs[] field properly.

---

.github/workflows/release-please-updates.yaml
.github/workflows/tests.yaml

chore: pin workflow to sha

---

.build/release.yaml

The release job needs to download the license files before running the docker build.

ci: fix the release build job so that it downloads licenses.

---

Makefile

Don't run yaml_fmt on .github/workflows. This is unnecessary and makes the code harder to read.

chore: omit yaml files in .github/workflows from yaml fmt.

---

.github/workflows/tests-main.yaml

Terraform has a hard time tearing down and recreating whole environments when they are 
too far out of date. Instead, this starts a brand new environment named 'ci-daily'. 
I will manually delete the old environment 'ci-main' to free up cloud resources.

ci: change name of ci environment to 'ci-branch-main' to avoid terraform issues

---

.github/workflows/release-please-updates.yaml
.github/workflows/tests.yaml

Take care of most `Pinned-Dependencies` and `Token-Permissions` alerts

chore: pin actions to SHA and make workflows read-all

---

infra/permissions/main.tf
infra/resources/gke_cluster.tf
infra/resources/private_gke_cluster.tf

This fixes a bug in the e2e test landscape where the latest node version reported by the GKE API is 1.26.* while the latest 
master version reported by the GKE API is 1.25.*, causing an error.

fix: The e2e k8s node pool version should match the master version

---

internal/workload/podspec_updates.go

This brings the healthchecks added to the proxy container in line with the recommendations 
in the cloud-sql-proxy [healthcheck docs](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/main/examples/k8s-health-check/README.md)

feat: Make proxy container healthchecks more resilient.

---

internal/workload/podspec_updates.go

This adds additional controls on the security context for pod containers to address these common 
k8s security best practices: 
- Run as a non-root user
- Mount container's root filesystem as read only
- Restrict Container from acquiring additional privileges

feat: Improve security posture of proxy containers.

---

Makefile

I increased the timeout to deploy the operator to e2e the test environments to 3 minutes. This should eliminate
one cause of false e2e job failures. Sometimes it takes more than than 90 seconds to deploy the operator 
to the e2e environment.

test: Increase the timeout waiting for the operator to deploy in e2e tests

---

internal/controller/pod_controller.go
internal/controller/pod_controller_test.go
internal/controller/setup.go
internal/workload/podspec_updates.go
internal/workload/podspec_updates_test.go

The pod cannot be configured to reliably instrument every single pod creation event due to limitations in the K8s API. 
Thus, the operator needs to listen for pod create and update events, to check if the pod is configured correctly. If the
pod is not configured correctly, and the pod is in an error or waiting state, the operator will delete the pod so that it can
be replaced. The replacement pod will be correctly configured by the webhook as it is created. 
Fixes #337

fix: delete misconfigured pods in error state.

---

internal/testintegration/integration_test.go

Repeating PR #369, which was merged incorrectly.

test: Add new integration test to delete misconfigured pods.

---

internal/controller/pod_controller.go
internal/controller/pod_controller_test.go
internal/workload/podspec_updates.go
internal/workload/podspec_updates_test.go

The case of "off" in "CrashLoopBackoff" needs to be capitalized in order for the comparison check to match in podspec_updates.go
Fixes #386

fix: Case issue with pod State (#386)

---

docs/examples/deployment-mssql-tcp.yaml
docs/examples/deployment-mysql-tcp.yaml
docs/examples/deployment-postgres-tcp.yaml

Fixes #433 
Adds resource allocation configurations to the examples. The resource requests are configured with the side-car container default resource request values. Follows the approach on this [PR](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/774)

doc: include example resource requests

---

internal/testhelpers/resources.go
internal/workload/podspec_updates.go
internal/workload/podspec_updates_test.go

Add the following configuration to the workload pods so that the proxy can gracefully exit
when the main container is done.
Configure the proxy container to exit 0 when it is terminated. Send a SIGTERM to the proxy container. We want 
the proxy to exit with code 0, indicating a clean termination. Without this change the proxy container would 
exit with exit code 140 (meaning terminated), which would cause kubernetes to report the 
pod as "exited in an error state."
Configure a workload lifecycle handler so that kubernetes calls GET /quitquitquit before terminating the proxy container.
This should give the proxy container the chance to exit gracefully before kubernetes sends a SIGTERM to the 
proxy process. 
Always enable the /quitquitquit proxy api. 
Always set the CSQL_QUIT_URLS …

feat: Configure proxy container for graceful termination

---

Makefile

We need to automatically format the yaml in config/ because some of it is generated
by controller-runtime and kubebuilder, some of it is hand-written. The formatter helps us
preserve the consistency and minimize noisy diffs when we upgrade the tools that generate yaml. 
However, we don't want to format the hand-written yaml used elsewhere in this project as tool configuration
and example docs. The yaml formatter makes the yaml consistent, but not as readable.

chore: Fix yaml formatter so that it only formats the config/ directory

---

internal/testhelpers/resources.go
internal/workload/podspec_updates.go
internal/workload/podspec_updates_test.go

All proxy and operator-related environment variables need to use the prefix CSQL_PROXY_ for consistency. 
Related to #361

fix: Correct the name of the quit url envvar CSQL_PROXY_QUIT_URLS.

---

docs/examples/deployment-postgres-unix.yaml

This provides a new example of how to configure your application to use a unix socket.

docs: Add a postgres unix example to actually use a unix socket.

---

.github/labels.yml
.github/workflows/tests.yaml

I added a new test trigger when the label 'tests: run-unit' is added. This is used for deps builds so that they don't run the e2e tests.

chore: Make it remove the 'tests:run-unit' label.

---

config/webhook/core_webhook.yaml
installer/cloud-sql-proxy-operator.yaml

fix: configure webhook to ignore kube-system

---

config/crd/bases/cloudsql.cloud.google.com_authproxyworkloads.yaml
config/rbac/role.yaml
installer/cloud-sql-proxy-operator.yaml

This is a temporary fix until we remove the generated code.
Related to #508

chore: fix generated code copyright year

---

.github/workflows/codeql.yml
.github/workflows/tests-main.yaml
.github/workflows/tests.yaml
Dockerfile-operator
go.mod
go.sum

This is currently failing on a similar issue to
https://github.com/kubernetes-sigs/controller-tools/issues/880

chore: bump to Go 1.22

---

.github/renovate.json

This will make sure that Renovate puts all the dependency updates in a single PR, rather than 1 per dependency.

chore: Configure renovate to group gomod updates in a single PR.

---

.github/renovate.json

This removes unnecessary configuration so that Renovate will use its defaults. This also puts the package groups
in a more sensible order.

chore: Simplify renovate config so it groups dependencies better.

---

docs/examples/deployment-mssql-tcp.yaml
docs/examples/deployment-mysql-tcp.yaml
docs/examples/deployment-postgres-tcp.yaml
docs/quick-start.md

Hello,
This PR aims to fix one issue and apply one finOps best practices:
- Delete env vars `DB_PORT` and `DB_HOST` from `deployment` because they are both automatically set by the operator
- Add the `privateIP: true` to reduce network billing
I also feel the `AuthProxyWorkload` should apply to a label selector so it could match multiple deployments, instead of a single deployment name. I did not include this change in this PR as it is not relevant to how the CSP works :-)
```
workloadSelector:
kind: Deployment
selector:
matchLabels:
cloud-proxy-sql: "true"
```
Regards,
Sebastien.

fix(examples): do not manually set env vars in deployment

---

Dockerfile
Dockerfile-operator
Makefile
infra/permissions/main.tf
infra/resources/main.tf
internal/workload/podspec_updates.go

Upgrade the Auth Proxy to 2.16.0, along with other library dependencies.

deps: Update dependencies to latest.

---

docs/api.md
internal/api/v1/authproxyworkload_types.go
internal/workload/podspec_updates.go
internal/workload/podspec_updates_test.go

This adds a new field to the AuthProxyWorkload spec: `authProxyContainer.securityContext`. This field will override the default security in the auth proxy container. 
Fixes #694
See also #641

feat: Specify the security context on the proxy container.

---

internal/workload/podspec_updates.go

Operator will use the proxy that includes the fix to the check DNS name changed loop. 
See https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/pull/1007

fix: Update proxy to 2.18.2 to include DNS name fix.

---

README.md

Updated the docs based on github issue #705

docs: Updated readme with new rationalle for using the operator.
